library(httr)
library(sqldf)
library(dplyr)
# REMOVE TO LINK url TO THE zip FILE # url <- "https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip" 
# REMOVE TO DOWNLOAD THE ZIP FILE    # GET(url, write_disk(basename(url), overwrite=TRUE))
# REMOVE TO UNPACK THE ZIP FILE      # unzip(basename(url))
xteData<-read.table("./UCI HAR Dataset/test/X_test.txt")
xtrData<-read.table("./UCI HAR Dataset/train/X_train.txt")
xData<-rbind(xteData, xtrData)
yteData<-read.table("./UCI HAR Dataset/test/Y_test.txt")
ytrData<-read.table("./UCI HAR Dataset/train/Y_train.txt")
yData<-rbind(yteData, ytrData)
subteData<-read.table("./UCI HAR Dataset/test/Subject_test.txt")
subtrData<-read.table("./UCI HAR Dataset/train/Subject_train.txt")
subData<-rbind(subteData, subtrData)
titleData<-read.table("./UCI HAR Dataset/features.txt")
titleData$V3<-paste(gsub("[-$%()]",".",titleData$V2),".mean..", sep="")
featTitles<-t(subset(titleData, select = 3))
colnames(xData) <- c(featTitles)
xsData<-xData[,c(unlist(sqldf("select V1 from titleData where V2 like '%mean()%' or V2 like '%std%' or V2 like '%Mean)'")))]
actTable<-read.table("./UCI HAR Dataset/activity_labels.txt")
yaData <- sqldf("SELECT V2 FROM yData JOIN actTable USING(V1)")
nxsData<-cbind(yaData, xsData)
colnames(nxsData)[1] <- "aCtivity"
rm(xData, xteData, xtrData, yData, yteData, ytrData, subteData, subtrData, titleData, featTitles, actTable)
snxsData<-cbind(subData, nxsData)
colnames(snxsData)[1] <- "sUbject"
gsnxsData<-group_by(snxsData, sUbject, aCtivity)
sgsnxsData<-summarise_each(gsnxsData, funs(mean))
write.table(sgsnxsData, file="ActivityDataMeansGroupedBySubAct.txt", row.names=FALSE)